"""Curated recurring-event calendar (US-centric, some global) mapped to focus
categories, with SKU-level product hints for what tends to trend around each.

These are well-known *recurring* events with known months — used to seed the
event calendar so upcoming catalysts are visible even before news breaks. Dates
are recurring-window estimates (month-level); specific player/lot names are
filled in by the News + Extraction agents from live evidence (never fabricated).

Each entry:
  name, event_type, month (1-12), day (or None), focus_categories,
  product_hints (SKU/category-level), importance (0..1), country
"""
from __future__ import annotations

CURATED_EVENTS: list[dict] = [
    # ---- Sports (drive cards + memorabilia + autographs) -------------------
    {"name": "Super Bowl", "event_type": "championship", "month": 2, "day": 9,
     "focus_categories": ["Trading Cards", "Sports Memorabilia", "Autographs"],
     "product_hints": ["Super Bowl MVP rookie cards", "championship team signed jerseys",
                       "game-used football memorabilia", "Panini Prizm Football rookie autos"],
     "importance": 0.95, "country": "United States"},
    {"name": "NBA All-Star Weekend", "event_type": "tournament", "month": 2, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia"],
     "product_hints": ["All-Star rookie cards", "Prizm Basketball parallels", "signed basketballs"],
     "importance": 0.7, "country": "United States"},
    {"name": "MLB Opening Day", "event_type": "sports milestone", "month": 3, "day": 27,
     "focus_categories": ["Trading Cards", "Sports Memorabilia"],
     "product_hints": ["Topps Series 1 rookie cards", "Bowman Chrome prospects", "signed baseballs"],
     "importance": 0.75, "country": "United States"},
    {"name": "NCAA March Madness Final Four", "event_type": "tournament", "month": 3, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia"],
     "product_hints": ["draft-class rookie cards", "college basketball autographs"],
     "importance": 0.7, "country": "United States"},
    {"name": "The Masters (golf)", "event_type": "tournament", "month": 4, "day": None,
     "focus_categories": ["Sports Memorabilia", "Autographs"],
     "product_hints": ["signed golf flags", "champion memorabilia"],
     "importance": 0.6, "country": "United States"},
    {"name": "NFL Draft", "event_type": "sports milestone", "month": 4, "day": 24,
     "focus_categories": ["Trading Cards"],
     "product_hints": ["rookie cards", "draft-class autographs", "Prizm Football rookies"],
     "importance": 0.85, "country": "United States"},
    {"name": "NBA Finals", "event_type": "championship", "month": 6, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia", "Autographs"],
     "product_hints": ["Finals MVP cards", "rookie autographs", "championship memorabilia",
                       "Prizm Basketball parallels"],
     "importance": 0.9, "country": "United States"},
    {"name": "NHL Stanley Cup Final", "event_type": "championship", "month": 6, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia"],
     "product_hints": ["Upper Deck Young Guns rookies", "signed hockey memorabilia"],
     "importance": 0.7, "country": "United States"},
    {"name": "NBA Draft", "event_type": "sports milestone", "month": 6, "day": 26,
     "focus_categories": ["Trading Cards"],
     "product_hints": ["rookie cards", "1-of-1 draft autos"],
     "importance": 0.8, "country": "United States"},
    {"name": "National Sports Collectors Convention", "event_type": "convention/event appearance",
     "month": 7, "day": 30, "focus_categories": ["Trading Cards", "Sports Memorabilia", "Autographs"],
     "product_hints": ["convention-exclusive cards", "signed memorabilia", "graded card deals"],
     "importance": 0.85, "country": "United States"},
    {"name": "Baseball Hall of Fame Induction", "event_type": "award", "month": 7, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia", "Autographs"],
     "product_hints": ["inductee rookie cards", "signed plaques and baseballs"],
     "importance": 0.75, "country": "United States"},
    {"name": "MLB World Series", "event_type": "championship", "month": 10, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia", "Autographs"],
     "product_hints": ["World Series rookie cards", "signed baseballs", "championship memorabilia",
                       "Topps Update rookies"],
     "importance": 0.9, "country": "United States"},
    {"name": "Formula 1 Season (Grand Prix window)", "event_type": "tournament", "month": 5, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia"],
     "product_hints": ["Topps Formula 1 Chrome cards", "driver autographs", "race-used memorabilia"],
     "importance": 0.7, "country": "United States"},
    {"name": "UFC Marquee Title Card", "event_type": "championship", "month": 7, "day": None,
     "focus_categories": ["Trading Cards", "Autographs"],
     "product_hints": ["Panini UFC Prizm rookies", "fighter autographs"],
     "importance": 0.65, "country": "United States"},
    {"name": "WWE WrestleMania", "event_type": "championship", "month": 4, "day": None,
     "focus_categories": ["Trading Cards", "Entertainment Memorabilia", "Autographs"],
     "product_hints": ["Panini WWE Prizm cards", "signed event memorabilia"],
     "importance": 0.7, "country": "United States"},

    # ---- Entertainment / Comics / Toys -------------------------------------
    {"name": "San Diego Comic-Con", "event_type": "convention/event appearance", "month": 7, "day": 24,
     "focus_categories": ["Comic Books and Memorabilia", "Entertainment Memorabilia", "Toys and Hobbies"],
     "product_hints": ["SDCC exclusive Funko Pops", "convention-exclusive figures",
                       "key comic issues", "signed comics"],
     "importance": 0.9, "country": "United States"},
    {"name": "New York Comic Con", "event_type": "convention/event appearance", "month": 10, "day": None,
     "focus_categories": ["Comic Books and Memorabilia", "Toys and Hobbies", "Entertainment Memorabilia"],
     "product_hints": ["NYCC exclusive collectibles", "variant comics", "exclusive figures"],
     "importance": 0.8, "country": "United States"},
    {"name": "Toy Fair (Spring)", "event_type": "official announcement", "month": 2, "day": None,
     "focus_categories": ["Toys and Hobbies"],
     "product_hints": ["upcoming LEGO sets", "new action figure lines", "preorder exclusives"],
     "importance": 0.65, "country": "United States"},
    {"name": "Star Wars Celebration", "event_type": "convention/event appearance", "month": 4, "day": None,
     "focus_categories": ["Toys and Hobbies", "Entertainment Memorabilia", "Trading Cards"],
     "product_hints": ["Star Wars exclusive figures", "Topps Star Wars cards", "signed props"],
     "importance": 0.7, "country": "United States"},

    # ---- Vinyl / Music -----------------------------------------------------
    {"name": "Record Store Day", "event_type": "limited drop", "month": 4, "day": 12,
     "focus_categories": ["Vinyl Records"],
     "product_hints": ["RSD-exclusive vinyl pressings", "limited colored vinyl", "reissue LPs"],
     "importance": 0.85, "country": "United States"},
    {"name": "Record Store Day Black Friday", "event_type": "limited drop", "month": 11, "day": 28,
     "focus_categories": ["Vinyl Records"],
     "product_hints": ["Black Friday exclusive vinyl", "limited pressings"],
     "importance": 0.75, "country": "United States"},
    {"name": "Grammy Awards", "event_type": "award", "month": 2, "day": None,
     "focus_categories": ["Vinyl Records", "Entertainment Memorabilia"],
     "product_hints": ["winning-artist vinyl reissues", "anniversary pressings"],
     "importance": 0.6, "country": "United States"},

    # ---- Coins -------------------------------------------------------------
    {"name": "ANA World's Fair of Money", "event_type": "convention/event appearance", "month": 8, "day": None,
     "focus_categories": ["Coins"],
     "product_hints": ["rare US coins", "commemorative releases", "graded key-date coins"],
     "importance": 0.75, "country": "United States"},
    {"name": "US Mint Annual Product Release Window", "event_type": "product release", "month": 1, "day": None,
     "focus_categories": ["Coins"],
     "product_hints": ["new commemorative coins", "proof sets", "American Eagle releases"],
     "importance": 0.65, "country": "United States"},

    # ---- Watches -----------------------------------------------------------
    {"name": "Watches and Wonders Geneva", "event_type": "official announcement", "month": 4, "day": None,
     "focus_categories": ["Watches"],
     "product_hints": ["new watch reference releases", "limited-edition watches", "discontinued models"],
     "importance": 0.8, "country": "Switzerland"},
    {"name": "Major Watch Auction Season (Phillips/Christie's)", "event_type": "auction result",
     "month": 5, "day": None, "focus_categories": ["Watches"],
     "product_hints": ["vintage Rolex/Patek lots", "record-setting references"],
     "importance": 0.7, "country": "United States"},

    # ---- Auctions / Art ----------------------------------------------------
    {"name": "Goldin Monthly Elite Auction", "event_type": "auction result", "month": 0, "day": None,
     "focus_categories": ["Trading Cards", "Sports Memorabilia", "Autographs"],
     "product_hints": ["high-grade rookie cards", "game-used memorabilia lots", "1-of-1 cards"],
     "importance": 0.7, "country": "United States", "recurring_monthly": True},
    {"name": "Heritage Auctions Signature Sales", "event_type": "auction result", "month": 0, "day": None,
     "focus_categories": ["Comic Books and Memorabilia", "Coins", "Trading Cards", "Entertainment Memorabilia"],
     "product_hints": ["key comic issues", "rare coins", "high-grade cards", "movie props"],
     "importance": 0.75, "country": "United States", "recurring_monthly": True},
    {"name": "Christie's / Sotheby's Marquee Sales", "event_type": "auction result", "month": 5, "day": None,
     "focus_categories": ["Entertainment Memorabilia", "Watches", "Collectibles"],
     "product_hints": ["fine art lots", "important watches", "historic memorabilia"],
     "importance": 0.7, "country": "United States"},
    {"name": "Art Basel Miami Beach", "event_type": "convention/event appearance", "month": 12, "day": 4,
     "focus_categories": ["Collectibles", "Entertainment Memorabilia"],
     "product_hints": ["contemporary art editions", "limited art prints", "gallery exclusives"],
     "importance": 0.65, "country": "United States"},

    # ---- Festivals / Seasonal (broad demand) -------------------------------
    {"name": "Black Friday / Cyber Monday", "event_type": "cultural trend", "month": 11, "day": 28,
     "focus_categories": ["Trading Cards", "Toys and Hobbies", "Collectibles", "Vinyl Records"],
     "product_hints": ["sealed hobby boxes", "limited toy drops", "exclusive bundles"],
     "importance": 0.85, "country": "United States"},
    {"name": "Holiday Gifting Season", "event_type": "cultural trend", "month": 12, "day": 1,
     "focus_categories": ["Trading Cards", "Toys and Hobbies", "Collectibles", "Coins", "Vinyl Records"],
     "product_hints": ["blaster/retail boxes", "gift-set collectibles", "commemorative coins"],
     "importance": 0.8, "country": "United States"},
    {"name": "Halloween", "event_type": "cultural trend", "month": 10, "day": 31,
     "focus_categories": ["Toys and Hobbies", "Entertainment Memorabilia"],
     "product_hints": ["horror-franchise figures", "limited seasonal collectibles"],
     "importance": 0.55, "country": "United States"},
    {"name": "Back-to-School Collecting Season", "event_type": "cultural trend", "month": 9, "day": 1,
     "focus_categories": ["Trading Cards", "Toys and Hobbies"],
     "product_hints": ["retail card packs", "starter collectibles"],
     "importance": 0.5, "country": "United States"},
]
